parameters:
  - name: azureConnection
    default: ""
  - name: rgName
    default: ""
  - name: file
    default: ""
  - name: params
    default: ""

stages:
  - stage: Deploy
    jobs:
      - job: CreateInfrastructure
        displayName: Create infrastructure
        steps:
          - task: AzureCLI@2
            name: Deploy
            displayName: Deploy to Azure
            inputs:
              azureSubscription: ${{ parameters.azureConnection }}
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az deployment group create \
                  --name "dep-${{ parameters.rgName }}-$(Build.BuildNumber)" \
                  --resource-group ${{ parameters.rgName }} \
                  --template-file ${{ parameters.file }} \
                  --parameters ${{ parameters.params }}
      - job: UpdateLibrary
        displayName: Add outputs to Library
        dependsOn: CreateInfrastructure
        steps:
          - task: AzurePowerShell@5
            name: SaveOutputs
            displayName: Save outputs to global group
            inputs:
              azureSubscription: ${{ parameters.azureConnection }}
              ScriptType: "InlineScript"
              Inline: |
                az devops configure `
                  --defaults `
                    organization="$(System.TeamFoundationCollectionUri)" `
                    project="$(System.TeamProject)" `
                  --use-git-aliases true

                $vg_id = az pipelines variable-group list `
                  --group-name globalGroup `
                  --query "[].id" `
                  --output tsv

                $deployment = Get-AzResourceGroupDeployment `
                  -ResourceGroupName "${{ parameters.rgName }}" `
                  -Name "dep-${{ parameters.rgName }}-$(Build.BuildNumber)"

                if (![string]::IsNullOrWhiteSpace($deployment)) {
                  foreach ($raw_output in $deployment.Outputs.GetEnumerator()) {
                    $name = $raw_output.Key
                    $value = $raw_output.Value.Value

                    $var_exist = az pipelines variable-group variable list `
                      --group-id "$vg_id" `
                      --query "$name" `
                      --output tsv

                    $vg_action = "update"

                    if ([string]::IsNullOrWhiteSpace($var_exist)) {
                      $vg_action = "create"
                    }

                    az pipelines variable-group variable "$vg_action" `
                      --group-id "$vg_id" `
                      --name "$name" `
                      --value "$value"
                  }
                }
              azurePowerShellVersion: "LatestVersion"
              pwsh: true
            env:
              AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
