trigger:
  - hypermaster

variables:
  - group: pipesConfig
  - group: prod

  - name: file
    value: $(Build.SourcesDirectory)/templates/missionctl.bicep
  - name: params
    value: dnsDomain=$(dnsDomain) crSku=Basic

pool:
  vmImage: $(vmImage)

stages:
  - template: modules/bicep-validate.yaml
    parameters:
      azureConnection: $(azureConnection)
      rgName: $(rgName)
      rgLocation: $(rgLocation)
      file: $(file)
      params: $(params)

  - template: modules/bicep-deploy.yaml
    parameters:
      azureConnection: $(azureConnection)
      rgName: $(rgName)
      rgLocation: $(rgLocation)
      file: $(file)
      params: $(params)
