trigger:
  - hypermaster

variables:
  - group: globalGroup
  - group: missionCtlGroup

  - name: file
    value: $(Build.SourcesDirectory)/templates/missionctl.bicep
  - name: params
    value: dnsDomain=$(dnsDomain)

pool:
  vmImage: $(vmImage)

stages:
  # - template: modules/bicep-validate.yaml
  #   parameters:
  #     azureConnection: $(azureConnection)
  #     rgName: $(rgName)
  #     rgLocation: $(rgLocation)
  #     file: $(file)
  #     params: $(params)

  - template: modules/bicep-deploy.yaml
    parameters:
      azureConnection: $(azureConnection)
      rgName: $(rgName)
      file: $(file)
      params: $(params)
