trigger: none

resources:
  repositories:
    - repository: app
      type: github
      name: nametoread/eschool-sorcery
      ref: hypermaster
      endpoint: nametoread
      trigger:
        - hypermaster

variables:
  - group: $(globalLibrary)
  - group: $(specificLibrary)

pool:
  vmImage: $(vmImage)

steps:
  - checkout: self
  - checkout: app
  - task: AzureCLI@2
    inputs:
      azureSubscription: "$(azureServiceConnection)"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        IMAGE='eschool'
        TAG='0.1-dev'

        az acr build \
          --resource-group $(resourceGroup) \
          --registry $(acrName) \
          --image ${IMAGE}:${TAG} .
      addSpnToEnvironment: true
      useGlobalConfig: true
      workingDirectory: "eschool-sorcery"
