trigger:
  - hypermaster

variables:
  - group: $(globalLibrary)
  - group: $(specificLibrary)

pool:
  vmImage: $(vmImage)

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az deployment sub create \
          --location $(location) \
          --template-file ./biceps/missionctl/main.bicep \
          --parameters \
            dnsDomain=$(dnsDomain)
