trigger:
  - hypermaster

variables:
  - group: globalGroup
  - group: dataGroup

  - name: file
    value: $(Build.SourcesDirectory)/2-data/main.bicep
  - name: params
    value: |
      vnName=$(vnName) \
      dbSubnetAddressIp=$(dbSubnetAddressIp)
      vnAddressSpaceIp=$(vnAddressSpaceIp) \
      dbName=$(dbName) \
      dbAdminLogin=$(dbAdminLogin) \
      dbAdminPassword="$(dbAdminPassword)"

pool:
  vmImage: $(vmImage)

stages:
  - template: ../modules/bicep-validate.yaml
    parameters:
      azureConnection: $(azureConnection)
      rgName: $(rgName)
      rgLocation: $(rgLocation)
      file: $(file)
      params: $(params)

  - template: ../modules/bicep-deploy.yaml
    parameters:
      azureConnection: $(azureConnection)
      rgName: $(rgName)
      file: $(file)
      params: $(params)
