trigger:
  - app-hypermaster

resources:
  repositories:
    - repository: app
      type: github
      name: nametoread/eschool-sorcery
      ref: app-hypermaster
      endpoint: nametoread
      trigger:
        - hypermaster

variables:
  - group: globalGroup
# - group: ciGroup

pool:
  vmImage: $(vmImage)

jobs:
  - job: BuildToAcr
    displayName: Build & push to ACR
    steps:
      - checkout: self
      - checkout: app
      - task: AzureCLI@2
        inputs:
          azureSubscription: "$(azureConnection)"
          scriptType: "bash"
          scriptLocation: "inlineScript"
          inlineScript: |
            IMAGE='eschool'
            TAG=$(Build.BuildNumber)

            az acr build \
              --resource-group $(crRg) \
              --registry $(crName) \
              --image ${IMAGE}:${TAG} \
              --image ${IMAGE}:latest .
          addSpnToEnvironment: true
          useGlobalConfig: true
          workingDirectory: "eschool-sorcery"
