parameters:
  - name: azureConnection
    default: ""
  - name: rgName
    default: ""
  - name: rgLocation
    default: ""
  - name: file
    default: ""
  - name: params
    default: ""

stages:
  - stage: Validate
    jobs:
      - job: LintBicep
        displayName: Lint Bicep code
        steps:
          - script: |
              az bicep build --file ${{ parameters.file }}
            name: LintBicepCode
            displayName: Run Bicep linter
      - job: ValidateBicep
        displayName: Validate Bicep code
        steps:
          - task: AzureCLI@2
            name: RunPreflightValidation
            displayName: Run preflight validation
            inputs:
              azureSubscription: ${{ parameters.azureConnection }}
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                TMP_RG=false
                if [ $(az group exists --name ${{ parameters.rgName }}) = false ]; then
                  TMP_RG=true
                  az group create --name ${{ parameters.rgName }} --location ${{ parameters.rgLocation }}
                fi

                az deployment group validate \
                  --resource-group ${{ parameters.rgName }} \
                  --template-file ${{ parameters.file }} \
                  --parameters ${{ parameters.params }}

                if [ "$TMP_RG" = true ] ; then
                  az group delete --name ${{ parameters.rgName }}
                fi
